project_id = "xawscxdrwzjzghshudpx"

[functions.generate-alternate-self]
verify_jwt = false

[functions.chat-with-parallel-self]
verify_jwt = false

[functions.generate-reflection]
verify_jwt = false

[functions.extract-memory]
verify_jwt = false